### ISSUE TITLE
Extra character in line 122

### ISSUE THREAD

**Issue by sftn-cferreira** [bfrankMS/AzStackHCI#1]
https://github.com/bfrankMS/AzStackHCI/blob/566701942c2872c0c5129a7753aaca7766c30bc2/AKS/AKS%2BARB.ps1#L122

Needs correction: (extra '-' between '-ostype' and 'linux'

New-AksHciCluster -Name $aksHciClusterName -nodeCount 1 -osType linux -primaryNetworkPlugin calico

**Comment by bfrankMS** [comment]
just updated this - thx.
